version: "2"
services:
  camunda:
    image: xhoopoe/camunda:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://db:5432/camunda
      - DB_USERNAME=camunda
      - DB_PASSWORD=camunda
      - WAIT_FOR=db:5432
  db:
    image: postgres
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=camunda
      - POSTGRES_USER=camunda
      - POSTGRES_PASSWORD=camunda
  # swagger-editor:
  #   image: swaggerapi/swagger-editor
  #   container_name: "swagger-editor"
  #   ports:
  #     - "8081:8080"
  #   environment:
  #     SWAGGER_JSON: /openapi.json

  # swagger-ui:
  #   image: swaggerapi/swagger-ui
  #   container_name: "swagger-ui"
  #   ports:
  #     - "8082:8080"
  #   volumes:
  #     - ./../api/openapi.json:/openapi.json
  #   environment:
  #     SWAGGER_JSON: /openapi.json
  #     API_URL: "http://84.201.143.226:8080/engine-rest"

