version: "2"
services:
  camunda:
    image: camunda/camunda-bpm-platform:latest
    ports:
      - $CAMUNDA_PORT:8080
    depends_on:
      - db
    env_file: .env
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://db:5432/camunda
      - DB_USERNAME=camunda
      - DB_PASSWORD=camunda
      - WAIT_FOR=db:$POSTGRES_PORT

  db:
    image: postgres
    restart: on-failure
    ports:
      - $POSTGRES_PORT:5432
    environment:
      - POSTGRES_DB=camunda
      - POSTGRES_USER=camunda
      - POSTGRES_PASSWORD=camunda

  front:
    image: ebiven/vue-cli
    depends_on:
      - server
    env_file: .env
    environment:
      - VUE_APP_SERVER_PORT=$SERVER_PORT
      - VUE_APP_SERVER_URL=$VUE_APP_SERVER_URL
    command: /bin/sh -c "npm install && npm run serve"
    volumes:
      - ./../front:/code
    ports:
      - $FRONT_PORT:8080

  server:
    image: clue/json-server
    command: /data/db.json --watch
    volumes:
      - ./../server:/server
      - ./../server/db.json:/data/db.json
    env_file: .env
    ports:
      - $SERVER_PORT:80

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    env_file: .env
    environment:
      - SWAGGER_JSON=workflow.yml
    ports:
      - $SWAGGER_UI_PORT:8080
    volumes:
      - ./../doc/workflow.yml:/workflow.yml
  # swagger-editor:
  #   image: swaggerapi/swagger-editor
  #   container_name: "swagger-editor"
  #   ports:
  #     - "8081:8080"
  #   environment:
  #     SWAGGER_JSON: /workflow.json
