version: "2"
services:
  camunda:
    image: camunda/camunda-bpm-platform:latest
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://db:5432/camunda
      - DB_USERNAME=camunda
      - DB_PASSWORD=camunda
      - WAIT_FOR=db:5432

  db:
    image: postgres
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=camunda
      - POSTGRES_USER=camunda
      - POSTGRES_PASSWORD=camunda

  front:
    image: otzhora/vue
    command: npm run serve
    volumes:
      - ./../front:/app
    ports:
      - 8081:8080

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - 8082:8080
    volumes:
      - ./../doc/workflow.yml:/workflow.yml
    environment:
      SWAGGER_JSON: /workflow.yml
