version: "2"
services:
  camunda:
    image: xhoopoe/camunda:latest
    ports:
      - $CAMUNDA_PORT:8080
    depends_on:
      - db
    env_file: .env
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://db:5432/camunda
      - DB_USERNAME=camunda
      - DB_PASSWORD=camunda
      - WAIT_FOR=db:$POSTGRES_PORT
      - STATUS_API_URL=localhost:$SERVER_PORT/status
      - SMS_API_KEY=$SMS_API_KEY

  db:
    image: postgres
    restart: on-failure
    ports:
      - $POSTGRES_PORT:5432
    volumes:
      - postgresql:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=camunda
      - POSTGRES_USER=camunda
      - POSTGRES_PASSWORD=camunda

  front:
    image: ebiven/vue-cli
    depends_on:
      - server
    env_file: .env
    environment:
      - VUE_APP_SERVER_PORT=$SERVER_PORT
      - VUE_APP_SERVER_URL=$VUE_APP_SERVER_URL
    command: /bin/sh -c "npm install && npm run serve"
    volumes:
      - ./../front:/code
    ports:
      - $FRONT_PORT:8080

  server:
    image: clue/json-server
    command: /data/db.json --watch
    volumes:
      - ./../server:/data
      - rest_server:/data
    env_file: .env
    ports:
      - $SERVER_PORT:80

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - $SWAGGER_UI_PORT:8080
    volumes:
      - ./../doc/facade_api.json:/facade_api.json
    environment:
      SWAGGER_JSON: /facade_api.json

  3dparty_api:
    image: node:8.16.1-alpine
    volumes:
      - ./../3dparty_api:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
    ports:
      - $SERVICES_FACADE_PORT:8084

volumes:
  rest_server:
  postgresql:
